version: "3.9"
services:
  mongo:
    image: "mongo:5.0"
    ports:
      - "42781:27017"
    volumes:
      - "mongo-volume:/data/db"
  api:
    build:
      context: "."
      dockerfile: "api.Dockerfile"
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
volumes:
  mongo-volume:
