[package]
name = "api"
version = "0.1.0"
edition = "2018"

[lib]
name = "api"
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bson = "2.1"
config = "0.11"
env_logger = "0.9"
log = "0.4"
mongodb = "2.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.15", features = ["full"] }
warp = "0.3"

[dev-dependencies]
lazy_static = "1.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
