on: push
name: PowerShell Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
